name: PoliticalAlignmentCaseStudy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - pyreadstats
  - scipy
  - statsmodels
  - pytables
  - pip
  - pip:
    - empiricaldist




